### ISSUE TITLE
Difference between this and volatile-register

### ISSUE THREAD

**Issue by hecatia-elegua** [rust-osdev/volatile#38]
japaric's [volatile-register](https://github.com/japaric/volatile-register), which is using japaric's [vcell](https://github.com/japaric/vcell/blob/master/src/lib.rs)

**Comment by phil-opp** [comment]
It not possible to implement a `VolatileCell` in a sound way at the moment because the compiler might insert spurious reads. See https://github.com/japaric/vcell/issues/10 and https://github.com/rust-lang/unsafe-code-guidelines/issues/411 for details.

In this crate, we try to create a sound abstraction for volatile access, based on raw pointers.
